# Generated by Django 4.2.4 on 2023-08-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransomwareapp', '0002_attackdata_encryptionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackdata',
            name='NumberOfFiles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attackdata',
            name='TotalFilesSize',
            field=models.IntegerField(),
        ),
    ]
