# Generated by Django 4.2.4 on 2023-08-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransomwareapp', '0004_attackdata_systemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackdata',
            name='EncryptionKey',
            field=models.BinaryField(max_length=100),
        ),
    ]
