# Generated by Django 4.2.4 on 2023-08-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ransomwareapp', '0006_remove_attackdata_totalfilessize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attackdata',
            old_name='TotalFileSize',
            new_name='TotalFilesSize',
        ),
    ]
