# Generated by Django 4.2.4 on 2023-09-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransomwareapp', '0007_rename_totalfilesize_attackdata_totalfilessize'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackdata',
            name='DecryptionPassword',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
