# Generated by Django 4.2.4 on 2023-09-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransomwareapp', '0008_attackdata_decryptionpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackdata',
            name='NumberOfFiles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attackdata',
            name='TotalFilesSize',
            field=models.IntegerField(),
        ),
    ]
